[ 2024-01-14 21:31:03,034 ] 33 root - INFO - Error Occurred while setting the connection
[ 2024-01-14 21:31:06,155 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getMe "HTTP/1.1 200 OK"
[ 2024-01-14 21:31:06,781 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/deleteWebhook "HTTP/1.1 200 OK"
[ 2024-01-14 21:31:06,784 ] 620 telegram.ext.Application - INFO - Application started
[ 2024-01-14 21:31:18,037 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:31:28,492 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:31:38,880 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:31:49,368 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:31:59,732 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:32:10,170 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:32:20,605 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:32:31,046 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:32:41,384 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:32:51,840 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:32:59,421 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:32:59,423 ] 45 root - INFO - Bot Started By user Shivansh
[ 2024-01-14 21:32:59,734 ] 612 root - ERROR - Exception while handling an update:
Traceback (most recent call last):
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\telegram\ext\_application.py", line 1234, in process_update
    await coroutine
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\telegram\ext\_basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\Desktop\Python\Projects\HTM\HTM_FINAL.py", line 46, in start
    database[colletion_name].insert_one({author: "hello there"})
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\collection.py", line 669, in insert_one
    self._insert_one(
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\collection.py", line 609, in _insert_one
    self.__database.client._retryable_write(acknowledged, _insert_command, session)
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\mongo_client.py", line 1523, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\mongo_client.py", line 1421, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\mongo_client.py", line 1462, in _retry_internal
    ).run()
      ^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\mongo_client.py", line 2416, in _write
    with self._client._checkout(self._server, self._session) as conn:
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\mongo_client.py", line 1252, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\pool.py", line 1637, in checkout
    conn = self._get_conn(handler=handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\pool.py", line 1756, in _get_conn
    conn = self.connect(handler=handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\pool.py", line 1607, in connect
    conn.authenticate()
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\pool.py", line 1078, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\auth.py", line 625, in authenticate
    auth_func(credentials, conn)
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\auth.py", line 530, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\auth.py", line 298, in _authenticate_scram
    res = conn.command(source, cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\helpers.py", line 322, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\pool.py", line 968, in command
    return command(
           ^^^^^^^^
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\network.py", line 192, in command
    helpers._check_command_response(
  File "C:\Users\Dell\anaconda3\envs\HTM\Lib\site-packages\pymongo\helpers.py", line 230, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'}
[ 2024-01-14 21:33:10,174 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:33:20,608 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:33:31,057 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:33:41,504 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:33:51,954 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:34:02,389 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:34:12,844 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:34:23,211 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:34:33,627 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:34:43,999 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:34:54,351 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:35:04,756 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:35:15,197 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:35:25,658 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:35:36,017 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:35:46,420 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:35:56,879 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:36:07,327 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:36:14,602 ] 1729 httpx - INFO - HTTP Request: POST https://api.telegram.org/bot6666820551:AAH4qD0_CXR1QacZkW6UXgzI0j5RvchCKhs/getUpdates "HTTP/1.1 200 OK"
[ 2024-01-14 21:36:14,605 ] 653 telegram.ext.Application - INFO - Application is stopping. This might take a moment.
[ 2024-01-14 21:36:14,605 ] 678 telegram.ext.Application - INFO - Application.stop() complete
